// Generated by Supabase. Do not edit by hand.
//
// Regenerate after every migration:
//   npm run types:supabase
//
// Source of truth: supabase/migrations/*.sql applied to project
// emwztkbxdafjujahxxcu.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      admin_emails: {
        Row: {
          created_at: string
          email: string
          note: string | null
        }
        Insert: {
          created_at?: string
          email: string
          note?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          note?: string | null
        }
        Relationships: []
      }
      booking_intents: {
        Row: {
          attribution: Json
          claimed_at: string | null
          created_at: string
          landing_page: string | null
          ref: string
          referrer: string | null
        }
        Insert: {
          attribution?: Json
          claimed_at?: string | null
          created_at?: string
          landing_page?: string | null
          ref: string
          referrer?: string | null
        }
        Update: {
          attribution?: Json
          claimed_at?: string | null
          created_at?: string
          landing_page?: string | null
          ref?: string
          referrer?: string | null
        }
        Relationships: []
      }
      lead_rejections: {
        Row: {
          answers: Json
          attribution: Json
          company: string | null
          created_at: string
          email: string | null
          id: string
          name: string | null
          platform: string | null
          reason: string
          reviewed_at: string | null
        }
        Insert: {
          answers?: Json
          attribution?: Json
          company?: string | null
          created_at?: string
          email?: string | null
          id?: string
          name?: string | null
          platform?: string | null
          reason: string
          reviewed_at?: string | null
        }
        Update: {
          answers?: Json
          attribution?: Json
          company?: string | null
          created_at?: string
          email?: string | null
          id?: string
          name?: string | null
          platform?: string | null
          reason?: string
          reviewed_at?: string | null
        }
        Relationships: []
      }
      case_studies: {
        Row: {
          body: string
          code: string
          created_at: string
          detail_sections: Json
          id: string
          intro: string
          metric_after: string | null
          metric_after_label: string | null
          metric_after_pct: number | null
          metric_before: string | null
          metric_before_label: string | null
          metric_before_pct: number | null
          metric_caption: string | null
          needs_confirmation: boolean
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["content_status"]
          status_label: string
          tags: string[]
          title: string
          updated_at: string
        }
        Insert: {
          body: string
          code: string
          created_at?: string
          detail_sections?: Json
          id?: string
          intro: string
          metric_after?: string | null
          metric_after_label?: string | null
          metric_after_pct?: number | null
          metric_before?: string | null
          metric_before_label?: string | null
          metric_before_pct?: number | null
          metric_caption?: string | null
          needs_confirmation?: boolean
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          status_label?: string
          tags?: string[]
          title: string
          updated_at?: string
        }
        Update: {
          body?: string
          code?: string
          created_at?: string
          detail_sections?: Json
          id?: string
          intro?: string
          metric_after?: string | null
          metric_after_label?: string | null
          metric_after_pct?: number | null
          metric_before?: string | null
          metric_before_label?: string | null
          metric_before_pct?: number | null
          metric_caption?: string | null
          needs_confirmation?: boolean
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          status_label?: string
          tags?: string[]
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      case_study_shots: {
        Row: {
          alt_text: string
          caption: string
          case_study_id: string
          created_at: string
          id: string
          section: string | null
          sort_order: number
          storage_path: string
        }
        Insert: {
          alt_text: string
          caption: string
          case_study_id: string
          created_at?: string
          id?: string
          section?: string | null
          sort_order?: number
          storage_path: string
        }
        Update: {
          alt_text?: string
          caption?: string
          case_study_id?: string
          created_at?: string
          id?: string
          section?: string | null
          sort_order?: number
          storage_path?: string
        }
        Relationships: [
          {
            foreignKeyName: "case_study_shots_case_study_id_fkey"
            columns: ["case_study_id"]
            isOneToOne: false
            referencedRelation: "case_studies"
            referencedColumns: ["id"]
          },
        ]
      }
      case_study_stats: {
        Row: {
          case_study_id: string
          created_at: string
          id: string
          label: string
          sort_order: number
          unit: string | null
          value: string
        }
        Insert: {
          case_study_id: string
          created_at?: string
          id?: string
          label: string
          sort_order?: number
          unit?: string | null
          value: string
        }
        Update: {
          case_study_id?: string
          created_at?: string
          id?: string
          label?: string
          sort_order?: number
          unit?: string | null
          value?: string
        }
        Relationships: [
          {
            foreignKeyName: "case_study_stats_case_study_id_fkey"
            columns: ["case_study_id"]
            isOneToOne: false
            referencedRelation: "case_studies"
            referencedColumns: ["id"]
          },
        ]
      }
      destinations: {
        Row: {
          config: Json
          created_at: string
          enabled: boolean
          id: string
          key: string
          label: string
          last_error: string | null
          last_error_at: string | null
          last_ok_at: string | null
          last_test_at: string | null
          last_test_message: string | null
          last_test_conclusive: boolean
          last_test_ok: boolean | null
          secret_last4: string | null
          secret_updated_at: string | null
          secret_vault_id: string | null
          test_event_code: string | null
          updated_at: string
        }
        Insert: {
          config?: Json
          created_at?: string
          enabled?: boolean
          id?: string
          key: string
          label: string
          last_error?: string | null
          last_error_at?: string | null
          last_ok_at?: string | null
          last_test_at?: string | null
          last_test_message?: string | null
          last_test_conclusive?: boolean
          last_test_ok?: boolean | null
          secret_last4?: string | null
          secret_updated_at?: string | null
          secret_vault_id?: string | null
          test_event_code?: string | null
          updated_at?: string
        }
        Update: {
          config?: Json
          created_at?: string
          enabled?: boolean
          id?: string
          key?: string
          label?: string
          last_error?: string | null
          last_error_at?: string | null
          last_ok_at?: string | null
          last_test_at?: string | null
          last_test_message?: string | null
          last_test_conclusive?: boolean
          last_test_ok?: boolean | null
          secret_last4?: string | null
          secret_updated_at?: string | null
          secret_vault_id?: string | null
          test_event_code?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      event_deliveries: {
        Row: {
          attempt_count: number
          created_at: string
          destination: string
          event_id: string
          id: string
          response_body: string | null
          response_code: number | null
          sent_at: string | null
          skipped_reason: string | null
          status: Database["public"]["Enums"]["delivery_status"]
          updated_at: string
        }
        Insert: {
          attempt_count?: number
          created_at?: string
          destination: string
          event_id: string
          id?: string
          response_body?: string | null
          response_code?: number | null
          sent_at?: string | null
          skipped_reason?: string | null
          status?: Database["public"]["Enums"]["delivery_status"]
          updated_at?: string
        }
        Update: {
          attempt_count?: number
          created_at?: string
          destination?: string
          event_id?: string
          id?: string
          response_body?: string | null
          response_code?: number | null
          sent_at?: string | null
          skipped_reason?: string | null
          status?: Database["public"]["Enums"]["delivery_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "event_deliveries_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      event_map: {
        Row: {
          created_at: string
          dedup_key: string | null
          destinations: string[]
          event_name: string
          id: string
          last_fired_at: string | null
          parameters: Json
          status: string
          trigger_description: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          dedup_key?: string | null
          destinations?: string[]
          event_name: string
          id?: string
          last_fired_at?: string | null
          parameters?: Json
          status?: string
          trigger_description?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          dedup_key?: string | null
          destinations?: string[]
          event_name?: string
          id?: string
          last_fired_at?: string | null
          parameters?: Json
          status?: string
          trigger_description?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      events: {
        Row: {
          consent: Json
          event_id: string
          event_name: string
          id: string
          occurred_at: string
          page_path: string | null
          params: Json
          received_at: string
          session_id: string | null
        }
        Insert: {
          consent?: Json
          event_id: string
          event_name: string
          id?: string
          occurred_at: string
          page_path?: string | null
          params?: Json
          received_at?: string
          session_id?: string | null
        }
        Update: {
          consent?: Json
          event_id?: string
          event_name?: string
          id?: string
          occurred_at?: string
          page_path?: string | null
          params?: Json
          received_at?: string
          session_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "events_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["session_id"]
          },
        ]
      }
      faqs: {
        Row: {
          answer: string
          created_at: string
          id: string
          published: boolean
          question: string
          sort_order: number
          source_key: string | null
          updated_at: string
        }
        Insert: {
          answer: string
          created_at?: string
          id?: string
          published?: boolean
          question: string
          sort_order?: number
          source_key?: string | null
          updated_at?: string
        }
        Update: {
          answer?: string
          created_at?: string
          id?: string
          published?: boolean
          question?: string
          sort_order?: number
          source_key?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      leads: {
        Row: {
          answers: Json
          campaign: string | null
          wbraid: string | null
          li_fat_id: string | null
          last_touch_term: string | null
          last_touch_source: string | null
          last_touch_medium: string | null
          last_touch_content: string | null
          last_touch_campaign: string | null
          last_referrer: string | null
          last_landing_page: string | null
          gbraid: string | null
          first_seen_at: string | null
          attribution_status: string
          origin: string
          canceled_at: string | null
          cancel_reason: string | null
          calendly_invitee_uri: string | null
          calendly_event_uri: string | null
          booked_at: string | null
          company: string | null
          consent: Json
          content: string | null
          created_at: string
          currency: string | null
          email: string
          fbclid: string | null
          gclid: string | null
          id: string
          landing_page: string | null
          medium: string | null
          msclkid: string | null
          name: string
          notes: string | null
          platform: string | null
          referrer: string | null
          session_id: string | null
          source: string | null
          status: Database["public"]["Enums"]["lead_status"]
          term: string | null
          ttclid: string | null
          updated_at: string
          value: number | null
        }
        Insert: {
          answers?: Json
          campaign?: string | null
          wbraid?: string | null
          li_fat_id?: string | null
          last_touch_term?: string | null
          last_touch_source?: string | null
          last_touch_medium?: string | null
          last_touch_content?: string | null
          last_touch_campaign?: string | null
          last_referrer?: string | null
          last_landing_page?: string | null
          gbraid?: string | null
          first_seen_at?: string | null
          attribution_status?: string
          origin?: string
          canceled_at?: string | null
          cancel_reason?: string | null
          calendly_invitee_uri?: string | null
          calendly_event_uri?: string | null
          booked_at?: string | null
          company?: string | null
          consent?: Json
          content?: string | null
          created_at?: string
          currency?: string | null
          email: string
          fbclid?: string | null
          gclid?: string | null
          id?: string
          landing_page?: string | null
          medium?: string | null
          msclkid?: string | null
          name: string
          notes?: string | null
          platform?: string | null
          referrer?: string | null
          session_id?: string | null
          source?: string | null
          status?: Database["public"]["Enums"]["lead_status"]
          term?: string | null
          ttclid?: string | null
          updated_at?: string
          value?: number | null
        }
        Update: {
          answers?: Json
          campaign?: string | null
          wbraid?: string | null
          li_fat_id?: string | null
          last_touch_term?: string | null
          last_touch_source?: string | null
          last_touch_medium?: string | null
          last_touch_content?: string | null
          last_touch_campaign?: string | null
          last_referrer?: string | null
          last_landing_page?: string | null
          gbraid?: string | null
          first_seen_at?: string | null
          attribution_status?: string
          origin?: string
          canceled_at?: string | null
          cancel_reason?: string | null
          calendly_invitee_uri?: string | null
          calendly_event_uri?: string | null
          booked_at?: string | null
          company?: string | null
          consent?: Json
          content?: string | null
          created_at?: string
          currency?: string | null
          email?: string
          fbclid?: string | null
          gclid?: string | null
          id?: string
          landing_page?: string | null
          medium?: string | null
          msclkid?: string | null
          name?: string
          notes?: string | null
          platform?: string | null
          referrer?: string | null
          session_id?: string | null
          source?: string | null
          status?: Database["public"]["Enums"]["lead_status"]
          term?: string | null
          ttclid?: string | null
          updated_at?: string
          value?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "leads_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["session_id"]
          },
        ]
      }
      offline_conversion_rows: {
        Row: {
          click_id: string | null
          click_id_kind: string | null
          conversion_time: string | null
          created_at: string
          currency: string | null
          id: string
          lead_id: string | null
          payload: Json | null
          reason: string | null
          result: Database["public"]["Enums"]["row_result"]
          upload_id: string
          value: number | null
        }
        Insert: {
          click_id?: string | null
          click_id_kind?: string | null
          conversion_time?: string | null
          created_at?: string
          currency?: string | null
          id?: string
          lead_id?: string | null
          payload?: Json | null
          reason?: string | null
          result: Database["public"]["Enums"]["row_result"]
          upload_id: string
          value?: number | null
        }
        Update: {
          click_id?: string | null
          click_id_kind?: string | null
          conversion_time?: string | null
          created_at?: string
          currency?: string | null
          id?: string
          lead_id?: string | null
          payload?: Json | null
          reason?: string | null
          result?: Database["public"]["Enums"]["row_result"]
          upload_id?: string
          value?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "offline_conversion_rows_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "offline_conversion_rows_upload_id_fkey"
            columns: ["upload_id"]
            isOneToOne: false
            referencedRelation: "offline_conversion_uploads"
            referencedColumns: ["id"]
          },
        ]
      }
      offline_conversion_uploads: {
        Row: {
          accepted_count: number
          conversion_action: string | null
          created_at: string
          currency: string | null
          destination: string
          dry_run: boolean
          id: string
          rejected_count: number
          result_message: string | null
          row_count: number
          status: Database["public"]["Enums"]["upload_status"]
          time_source: string | null
          value_source: string | null
        }
        Insert: {
          accepted_count?: number
          conversion_action?: string | null
          created_at?: string
          currency?: string | null
          destination: string
          dry_run?: boolean
          id?: string
          rejected_count?: number
          result_message?: string | null
          row_count?: number
          status?: Database["public"]["Enums"]["upload_status"]
          time_source?: string | null
          value_source?: string | null
        }
        Update: {
          accepted_count?: number
          conversion_action?: string | null
          created_at?: string
          currency?: string | null
          destination?: string
          dry_run?: boolean
          id?: string
          rejected_count?: number
          result_message?: string | null
          row_count?: number
          status?: Database["public"]["Enums"]["upload_status"]
          time_source?: string | null
          value_source?: string | null
        }
        Relationships: []
      }
      posts: {
        Row: {
          body: string[]
          canonical_url: string | null
          created_at: string
          id: string
          is_draft: boolean
          og_image_path: string | null
          published_at: string | null
          reading_time: string
          slug: string
          sort_order: number
          status: Database["public"]["Enums"]["content_status"]
          summary: string
          title: string
          topic: string
          updated_at: string
        }
        Insert: {
          body?: string[]
          canonical_url?: string | null
          created_at?: string
          id?: string
          is_draft?: boolean
          og_image_path?: string | null
          published_at?: string | null
          reading_time: string
          slug: string
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          summary: string
          title: string
          topic: string
          updated_at?: string
        }
        Update: {
          body?: string[]
          canonical_url?: string | null
          created_at?: string
          id?: string
          is_draft?: boolean
          og_image_path?: string | null
          published_at?: string | null
          reading_time?: string
          slug?: string
          sort_order?: number
          status?: Database["public"]["Enums"]["content_status"]
          summary?: string
          title?: string
          topic?: string
          updated_at?: string
        }
        Relationships: []
      }
      reviews: {
        Row: {
          a11y_label: string | null
          aspect_ratio: Database["public"]["Enums"]["aspect_ratio"] | null
          attribution: string | null
          client_name: string | null
          company: string | null
          created_at: string
          id: string
          is_placeholder: boolean
          published: boolean
          pull_quote: string | null
          quote: string | null
          rating: number | null
          sort_order: number
          source: string | null
          source_key: string | null
          thumbnail_url: string | null
          type: Database["public"]["Enums"]["review_type"]
          updated_at: string
          youtube_id: string | null
          youtube_url: string | null
        }
        Insert: {
          a11y_label?: string | null
          aspect_ratio?: Database["public"]["Enums"]["aspect_ratio"] | null
          attribution?: string | null
          client_name?: string | null
          company?: string | null
          created_at?: string
          id?: string
          is_placeholder?: boolean
          published?: boolean
          pull_quote?: string | null
          quote?: string | null
          rating?: number | null
          sort_order?: number
          source?: string | null
          source_key?: string | null
          thumbnail_url?: string | null
          type: Database["public"]["Enums"]["review_type"]
          updated_at?: string
          youtube_id?: string | null
          youtube_url?: string | null
        }
        Update: {
          a11y_label?: string | null
          aspect_ratio?: Database["public"]["Enums"]["aspect_ratio"] | null
          attribution?: string | null
          client_name?: string | null
          company?: string | null
          created_at?: string
          id?: string
          is_placeholder?: boolean
          published?: boolean
          pull_quote?: string | null
          quote?: string | null
          rating?: number | null
          sort_order?: number
          source?: string | null
          source_key?: string | null
          thumbnail_url?: string | null
          type?: Database["public"]["Enums"]["review_type"]
          updated_at?: string
          youtube_id?: string | null
          youtube_url?: string | null
        }
        Relationships: []
      }
      sessions: {
        Row: {
          consent: Json
          country: string | null
          device_type: Database["public"]["Enums"]["device_type"]
          event_count: number
          fbclid: string | null
          first_seen_at: string
          first_touch_campaign: string | null
          first_touch_content: string | null
          first_touch_medium: string | null
          first_touch_source: string | null
          first_touch_term: string | null
          gclid: string | null
          landing_page: string | null
          last_seen_at: string
          last_touch_campaign: string | null
          last_touch_content: string | null
          last_touch_medium: string | null
          last_touch_source: string | null
          last_touch_term: string | null
          msclkid: string | null
          referrer: string | null
          session_id: string
          ttclid: string | null
          user_agent: string | null
        }
        Insert: {
          consent?: Json
          country?: string | null
          device_type?: Database["public"]["Enums"]["device_type"]
          event_count?: number
          fbclid?: string | null
          first_seen_at?: string
          first_touch_campaign?: string | null
          first_touch_content?: string | null
          first_touch_medium?: string | null
          first_touch_source?: string | null
          first_touch_term?: string | null
          gclid?: string | null
          landing_page?: string | null
          last_seen_at?: string
          last_touch_campaign?: string | null
          last_touch_content?: string | null
          last_touch_medium?: string | null
          last_touch_source?: string | null
          last_touch_term?: string | null
          msclkid?: string | null
          referrer?: string | null
          session_id: string
          ttclid?: string | null
          user_agent?: string | null
        }
        Update: {
          consent?: Json
          country?: string | null
          device_type?: Database["public"]["Enums"]["device_type"]
          event_count?: number
          fbclid?: string | null
          first_seen_at?: string
          first_touch_campaign?: string | null
          first_touch_content?: string | null
          first_touch_medium?: string | null
          first_touch_source?: string | null
          first_touch_term?: string | null
          gclid?: string | null
          landing_page?: string | null
          last_seen_at?: string
          last_touch_campaign?: string | null
          last_touch_content?: string | null
          last_touch_medium?: string | null
          last_touch_source?: string | null
          last_touch_term?: string | null
          msclkid?: string | null
          referrer?: string | null
          session_id?: string
          ttclid?: string | null
          user_agent?: string | null
        }
        Relationships: []
      }
      settings: {
        Row: {
          calendly_url: string | null
          contact_email: string | null
          default_currency: string | null
          gtm_container_id: string | null
          id: boolean
          retention_days: number
          sgtm_endpoint: string | null
          site_name: string | null
          updated_at: string
        }
        Insert: {
          calendly_url?: string | null
          contact_email?: string | null
          default_currency?: string | null
          gtm_container_id?: string | null
          id?: boolean
          retention_days?: number
          sgtm_endpoint?: string | null
          site_name?: string | null
          updated_at?: string
        }
        Update: {
          calendly_url?: string | null
          contact_email?: string | null
          default_currency?: string | null
          gtm_container_id?: string | null
          id?: boolean
          retention_days?: number
          sgtm_endpoint?: string | null
          site_name?: string | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      public_site_settings: {
        Row: {
          gtm_container_id: string | null
        }
        Relationships: []
      }
      event_last_fired: {
        Row: {
          event_name: string | null
          last_fired_at: string | null
          event_count: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      is_admin: { Args: never; Returns: boolean }
      set_destination_secret: { Args: { p_key: string; p_secret: string }; Returns: undefined }
      clear_destination_secret: { Args: { p_key: string }; Returns: undefined }
      get_destination_secret: { Args: { p_key: string }; Returns: string }
      record_lead_rejection: {
        Args: {
          p_answers?: Json
          p_attribution?: Json
          p_company?: string
          p_email?: string
          p_name?: string
          p_platform?: string
          p_reason: string
        }
        Returns: string
      }
      record_booking: {
        Args: {
          p_answers?: Json
          p_booked_at?: string
          p_email: string
          p_event_uri: string
          p_invitee_uri: string
          p_name: string
          p_ref?: string
        }
        Returns: string
      }
      record_booking_cancellation: {
        Args: { p_canceled_at?: string; p_invitee_uri: string; p_reason?: string }
        Returns: string
      }
      submit_lead: {
        Args: {
          p_attribution?: Json
          p_name: string
          p_email: string
          p_company?: string
          p_platform?: string
          p_answers?: Json
          p_session_id?: string
        }
        Returns: string
      }
    }
    Enums: {
      aspect_ratio: "portrait" | "landscape"
      content_status: "draft" | "published"
      delivery_status: "pending" | "sent" | "failed" | "skipped"
      device_type: "desktop" | "mobile" | "tablet" | "bot" | "unknown"
      lead_status: "new" | "contacted" | "qualified" | "booked" | "won" | "lost"
      review_type: "video" | "written"
      row_result: "eligible" | "ineligible" | "accepted" | "rejected"
      upload_status: "draft" | "exported" | "uploaded" | "failed"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      aspect_ratio: ["portrait", "landscape"],
      content_status: ["draft", "published"],
      delivery_status: ["pending", "sent", "failed", "skipped"],
      device_type: ["desktop", "mobile", "tablet", "bot", "unknown"],
      lead_status: ["new", "contacted", "qualified", "booked", "won", "lost"],
      review_type: ["video", "written"],
      row_result: ["eligible", "ineligible", "accepted", "rejected"],
      upload_status: ["draft", "exported", "uploaded", "failed"],
    },
  },
} as const
